/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yGk1jShLiHT
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-full max-w-md">
        <Card>
          <CardHeader>
            <CardTitle>Video to Article</CardTitle>
            <CardDescription>Upload your video and get the article</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="video-link">Video Link</Label>
              <Input id="video-link" placeholder="Enter video link" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="video-file">Video File</Label>
              <Input id="video-file" type="file" />
            </div>
            <Button className="w-full" type="submit">
              Upload
            </Button>
          </CardContent>
        </Card>
        <Card className="mt-4">
          <CardHeader>
            <CardTitle>Result</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="article">Article</Label>
              <textarea
                className="w-full h-48 border rounded shadow p-2"
                id="article"
                placeholder="Article will be displayed here"
              />
            </div>
            <div className="space-y-2">
              <Button className="w-full" type="button">
                Download Article
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
